version: '1'
services:
  angular:
    build:
      context: .
    working_dir: /app
    ports:
      - 4200:4200
      - 9876:9876
    volumes:
      - ./:/app
      - /app/node_modules
    command: ./node_modules/.bin/ng serve --host 0.0.0.0
